### ISSUE TITLE
Would you be interested in a feature to shuffle queues?

### ISSUE THREAD

**Issue by juanformoso** [getmoto/moto#1493]
We'd like to add a test case to our code to simulate that amazon sqs returns messages in a different order than pushed, since the documentation says that although it's not common, they don't guarantee order.

Before adding that code to my application or making a "private" fork of moto, I wanted to ask you if you'd be interested in a PR with a feature that does that (shuffle the queues)

Regards

**Comment by JackDanger** [comment]
Because we keep the API strictly limited to only the actual AWS API I don't think we'd want a special API call (either internal or external) to shuffle the queues.
However, since out-of-order messages is indeed part of the SQS contract I think it would be great if, whenever at least a certain number of messages are in a queue (say, 10) that queue is shuffled. This would let you test the behavior you want and also not violate any assumptions other developers have. If anything it may harden many apps against the realities of AWS.

What do you think?

**Comment by bblommers** [comment]
Considering the lack of response here, and lack of upvotes/+1's, I'm going to assume this is not (or no longer) useful for people, so I'll close this.
