### ISSUE TITLE
Dynamodb batch_execute_statement not supported

### ISSUE THREAD

**Issue by evanhackett** [getmoto/moto#4223]
When running a batch_execute_statement, the following exception occurs:

```
AttributeError: 'DynamoHandler' object has no attribute 'batch_execute_statement'
```

Here is the complete trace:

```
>       result = app.lambda_handler(event, '')

tests/unit/test_merge_decode_results.py:51:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/decode_video_state_machine/merge_results/app.py:70: in lambda_handler
    results = get_data_from_secrets(secrets)
src/decode_video_state_machine/merge_results/app.py:52: in get_data_from_secrets
    results = dynamodb.batch_execute_statement(
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/client.py:357: in _api_call
    return self._make_api_call(operation_name, kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/client.py:662: in _make_api_call
    http, parsed_response = self._make_request(
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/client.py:682: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/endpoint.py:136: in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/endpoint.py:253: in _needs_retry
    responses = self._event_emitter.emit(
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:183: in __call__
    if self._checker(attempts, response, caught_exception):
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:250: in __call__
    should_retry = self._should_retry(attempt_number, response,
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:269: in _should_retry
    return self._checker(attempt_number, response, caught_exception)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:316: in __call__
    checker_response = checker(attempt_number, response,
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:222: in __call__
    return self._check_caught_exception(
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/retryhandler.py:359: in _check_caught_exception
    raise caught_exception
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/endpoint.py:197: in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/moto/core/models.py:322: in __call__
    status, headers, body = response_callback(
../../API-my-copy/API/venv/lib/python3.9/site-packages/moto/core/responses.py:202: in dispatch
    return cls()._dispatch(*args, **kwargs)
../../API-my-copy/API/venv/lib/python3.9/site-packages/moto/core/responses.py:312: in _dispatch
    return self.call_action()
../../API-my-copy/API/venv/lib/python3.9/site-packages/moto/core/utils.py:277: in _wrapper
    response = f(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <moto.dynamodb2.responses.DynamoHandler object at 0x1143d9d30>

    @amzn_request_id
    def call_action(self):
        self.body = json.loads(self.body or "{}")
        endpoint = self.get_endpoint_name(self.headers)
        if endpoint:
            endpoint = camelcase_to_underscores(endpoint)
>           response = getattr(self, endpoint)()
E           AttributeError: 'DynamoHandler' object has no attribute 'batch_execute_statement'

../../API-my-copy/API/venv/lib/python3.9/site-packages/moto/dynamodb2/responses.py:86: AttributeError
```

The code I'm running looks something like this:

```python
import boto3

dynamodb = boto3.client('dynamodb')

statements = ... # leaving this out because I believe it is irrelevant

results = dynamodb.batch_execute_statement(
    Statements=statements
)
```

The reason I raise this as an issue is because the readme for the project states that "all endpoints" are supported for DynamoDB2, which led me to believe that `batch_execute_statement` would be supported. I just wanted to check that this is indeed not supported, and so it is expected behavior.

**Comment by gtourkas** [comment]
@bblommers can I pick this up ?

**Comment by bblommers** [comment]
All yours @gtourkas! Let me know if you need any help

**Comment by gtourkas** [comment]
@bblommers 

Some points/questions:

1.  Since `batch_execute_statement` will be implemented, it also makes sense to implement `execute_statement` and perhaps `execute_transaction`. 
2. All these functions invoke [PartiQL](https://partiql.org/) queries/commands, which is an SQL-like dialect. Even though DynamoDB uses only a [subset](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.update.html) of PartiQL, with the most noticeable difference being the lack of support for JOINs, this does the raise the stakes a bit in terms of parsing. Now, I've noticed that you do have parsing facilities (ExpressionTokenizer) for expressions but this won't suffice SQL-like queries and commands. So the question is whether is it ok to work on a parsing facility using [Lark](https://github.com/lark-parser/lark) ? The idea is this will result in query or scan for SELECT, put_item for INSERT/UPDATE and delete_item for DELETE. For that point onwards, the current parsing/validation/execution kick in.

**Comment by bblommers** [comment]
1) The more, the merrier!

2) That would be very welcome, to have a parsing facility for PartiQL. I've looked into doing something similar for Athena, which also uses PartiQL, but never got around to any development work.

Just in case you haven't seen it: you might be able to borrow some work from https://github.com/ggszk/partiql-neo4j, it looks like they already have a grammar in Lark-format.

**Comment by ronkorving** [comment]
@bblommers Sorry to hijack this issue for my question, but it's related to the 2nd point raised above. `s3.select_object_content` (currently not implemented in moto) also uses some dialect of SQL, though I'm not sure what dialect it is. I have use-cases where I would benefit from using that API, but am avoiding it, because I can't test my code (because Moto doesn't support it). I suspect y'all are probably not happy with people creating tickets called "please implement API X", because I'm sure the goal is to support as many boto3 APIs as possible anyway. Maybe I don't really have a question beyond: If you're considering supporting SQL/PartiQL query support for a service like DynamoDB, could `s3.select_object_content` perhaps also be considered as a point of interest? Thank you for all the amazing work.

**Comment by bblommers** [comment]
We are considering it @ronkorving! See #3301, which already lays out some of the issues with implementing it.
Once we do have support for one, it should definitely be easy to add support for the other. 

Would you mind sharing the query that you use in the other ticket? Just to get a feel for the difficulty/how advanced our query support would need to be.

**Comment by ronkorving** [comment]
@bblommers I'm avoiding using it altogether right now, so can't provide an example query 😅 But appreciate you sharing the issue! I searched for `select_object_content` in the issue tracker and didn't find anything, but it seems my search wasn't broad enough. I'm thrilled to see interest in the matter.

**Comment by bblommers** [comment]
@evanhackett @gtourkas The `batch_execute_statement` and `execute_statement`-methods are now supported as of moto >= 4.1.8.dev14.
Support is still experimental - please see http://docs.getmoto.org/en/latest/docs/services/dynamodb.html for details. Feel free to raise a new issue if you run into any problems.

@ronkorving S3 Select has been part of Moto as of 4.1.6. Same idea - it's experimental, but feedback is always welcome!
