### ISSUE TITLE
Request: Add Python typing annotations

### ISSUE THREAD

**Issue by Mainstay-Noah-Huppert** [getmoto/moto#4944]
Hi. Thank you very much for this helpful library.

Would it be possible to add Python type annoations to the source code of this library? Or [MyPy typing stubs](https://mypy.readthedocs.io/en/stable/stubs.html)?

The benefit is that it would allow users to run a static type checker over their testing code which uses moto.

**Comment by bblommers** [comment]
Hi @Mainstay-Noah-Huppert, which parts of Moto do you use that would need type annotations?

Straightforward tests that only use the Moto-decorator wouldn't benefit from any typing, as far as I can see, as the test would only contain boto3-calls.

Note that I'm not against the idea, just trying to gauge the most efficient way of meeting your usecase.

**Comment by glungley** [comment]
Hi both, we have this issue, so maybe I can clarify.

When using moto with the decorators we get errors like the following:
`Untyped decorator makes function "x" untyped [misc]`

Although having types within moto itself would not be of any benefit to these tests. Having the decorators typed would mean we don't have to disable mypy for these tests and lose the value of having it for the boto3-calls.

**Comment by iainelder** [comment]
Python typing annotations would be really useful for developers too.

I just started looking at the Organizations module and I wish I had types :-)

All the backends should return the same types as the boto3 clients do. By following what [boto3-stubs](https://pypi.org/project/boto3-stubs/) declares for the real boto3 library, I think it would make the mocks easier to maintain.

Bert, would you accept taking on mypy as a dependency so that I may add type annotations to the Organizations module?

**Comment by bblommers** [comment]
> 
> All the backends should return the same types as the boto3 clients do. 

This is not necessarily true. Moto only intercepts the HTTP request that boto3 makes to AWS, so boto3 will still run a post-processing step after receiving the (mocked) response.
In a lot of cases, if we return a JSON-response it may look like the response from the boto3-client, but it's not guaranteed.

> Bert, would you accept taking on mypy as a dependency so that I may add type annotations to the Organizations module?

Are you suggesting to add it as a dev-dependency, and running mypy (on the organizations-module only, for now) as part of the linting-process? I'd be OK with that, yes.

**Comment by iainelder** [comment]
> Are you suggesting to add it as a dev-dependency, and running mypy (on the organizations-module only, for now) as part of the linting-process? I'd be OK with that, yes.

That's exactly what I was thinking. In my branch I've added mypy to the Makefile lint target and I've configured mypy to ignore everything except the organizations module and tests. That allows typing to be introduced gradually, and to ignore it where adding it is not worth the effort right now.

If you want to see how it works, you can check my branch https://github.com/iainelder/moto/tree/organizations-fixes (work in progress, of course). If nothing else, it's great training for working on #5034 because it's forcing me to read and understand all the module code first!

> This is not necessarily true. Moto only intercepts the HTTP request that boto3 makes to AWS, so boto3 will still run a post-processing step after receiving the (mocked) response.

I have discovered this while hacking on my idea. Timestamps, for example, are presented in the HTTP response in floating point unix time. Boto3 converts these to Python datetimes. For now I'm dealing with that by lying to the type checker via casting. But in the pipeline I have an idea about how to handle it more gracefully - do return real datetime objects from the service class and do the convertion to unix timestamp "wire format" in the response module. I'll see how it works out in practive.

**Comment by iainelder** [comment]
Thanks @bblommers for completing this. I got overwhelmed last year with other work and couldn't come back to this. Thanks for all your hard work on moto because it supports other projects I work on!

**Comment by bblommers** [comment]
No problem @iainelder! This is part of moto >= 4.1.12.dev29 - just let me know if you run into any issues.

**Comment by andersk** [comment]
The types can’t be used in downstream projects yet—mypy won’t be able to find them until a [`py.typed` marker file](https://peps.python.org/pep-0561/#packaging-type-information) is added to the package.

**Comment by andersk** [comment]
And the current annotations seem pretty broken, so adding `py.typed` right now would probably break most of those downstream projects.

```python
from moto import mock_s3

@mock_s3
def test() -> int:
    return 123

n: int = test()
```

```console
$ mypy test.py
test.py:7: error: Missing positional argument "func" in call to "__call__" of "BaseMockAWS"  [call-arg]
test.py:7: error: Incompatible types in assignment (expression has type "Callable[..., BaseMockAWS]", variable has type "int")  [assignment]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by bblommers** [comment]
Appreciate the feedback @andersk. I wasn't aware of the need to add `py.typed`.

So far we have type annotations working for three situations:
1. Using a regular test (
   ```
   @mock_s3
   def test() -> None:
   ```
2. Using a context manager (`with mock_s3(): ...`)
3. Using the manual mocks
    ```
    m = mock_s3()
    m.start()
    m.stop()
    ```

Support for decorating methods with a return-type is indeed broken for now. If anyone wants to have a crack at this, PR's are always welcome.


@adam-everest I'll probably wait until we get this sorted (provided it doesn't take too long)

**Comment by bblommers** [comment]
OK, I'm going to open this back up. The logic around decorators is quite complex, and I'm not sure it's possible to fix type annotations without refactoring the logic first. TBC.

FWIW, 4.1.12 has now been released! Just without the `py.typed` marker.

**Comment by bblommers** [comment]
Typing is now supported as of Moto 4.2.10, thanks to @tungol 's excellent work in #7045.

It has the `py.typed` marker, and supports methods with a return-type. I'll close this, but let us know if there are any issues that I've overlooked.
