### ISSUE TITLE
S3 backend leaks keys if used together with other backends

### ISSUE THREAD

**Issue by hannes-ucsc** [getmoto/moto#5913]
Continued from #5584. I'm encountering this in a test case that needs both S3 and DynamoDB mocked. Here's the smallest repro I can think of:

```python
$ python -Wall
Python 3.9.12 (main, Oct  8 2022, 00:52:50) 
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gc
>>> from moto.s3.models import S3Backend
>>> from moto.dynamodb.models import DynamoDBBackend
>>> from moto import __version__
>>> __version__
'4.1.2'
>>> s3 = S3Backend('us-west-1', '1234')
>>> db = DynamoDBBackend('us-west-1', '1234')
>>> s3.create_bucket('my-bucket','us-west-1')
<moto.s3.models.FakeBucket object at 0x104d57be0>
>>> s3.put_object('my-bucket','my-key', 'y')
<moto.s3.models.FakeKey object at 0x104d57c40>
>>> db.reset()
>>> s3.reset()
>>> gc.collect()
/Users/hannes/.venv/lib/python3.9/site-packages/moto/s3/models.py:349: ResourceWarning: S3 key was not disposed of in time
  warnings.warn("S3 key was not disposed of in time", ResourceWarning)
29269
>>> 
```

The issue seems to be that `BaseBackend.reset()` — via `._reset_model_refs()` — resets each model's `.instances` class attribute to an empty list so that when `S3Backend.reset()` attempts to properly dispose the `FakeKey` instances, that list in `FakeKey.instances` is already empty, and the key leaks. 

Maybe `_reset_model_refs()` should call `dispose()` on every model instance before resetting `.instances` to `[]`. That would mean that the `dispose()` protocol becomes part of every model.  Then again, it seems odd that one backend resets the models of another one. Maybe it should only reset its own models.

**Comment by bblommers** [comment]
Just to give some context: the `instances`-attribute is used to tell a user what is happening in the background, and which models have been created by Moto. This is only exposed when running MotoServer, where people can see the list of models/instances in the browser. 

The reason that one backend resets the models of another, is because an action in one backend can cause changes to another. 
Creating an S3 bucket, for example, can result in the creation of an Events-notification. This means that S3 cannot _just_ clean it's own models, as that would result in data being left behind.

There are probably two decent (non-invasive) ways to fix this problem:
 - Call `dispose()` on every instance, as you suggest
 - Override ` _reset_model_refs` in S3, and call dispose only on FakeKey-objects

I'll have a look later on to see what works best.

FWIW - the ideal way to solve this would include getting rid of the `instances`-attribute altogether, and find a better (more flexible, less hacky) way to expose the inner data to users, but that is an architectural overhaul that I'm not quite willing to commit to atm.
