### ISSUE TITLE
Deploying Terraform to Moto

### ISSUE THREAD

**Issue by WesleyHindle** [getmoto/moto#5978]
Is there a way to deploy AWS infra using Terraform which would create the resources in moto? Just as a way to test the infra that is being deployed, rather than actually deploying it to AWS.

**Comment by bblommers** [comment]
Hey @WesleyHindle, you can when using Moto server.

See our docs here, the Example Usage section also contains an example for Terraform:
https://docs.getmoto.org/en/latest/docs/server_mode.html

**Comment by WesleyHindle** [comment]
I'm able to deploy TF infra using the local server, however when I go to test this with moto the resource isn't being picked up:

```hcl
provider "aws" {
  region                      = "us-east-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    s3_use_path_style         = true

  endpoints {
    s3       = "http://localhost:5000"
    lambda           = "http://localhost:5000"
  }
}

resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.b.id
  acl    = "private"
}
```

```python
import boto3
from moto import mock_s3
import os
import pytest

@pytest.fixture
@mock_s3
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"

@pytest.fixture
def s3_client(aws_credentials):
    with mock_s3():
        yield boto3.client("s3")


def test_client_created(s3_client):
    users = s3_client.list_buckets()
    print(users)
```

This returns, with empty buckets:
```bash
{'ResponseMetadata': {'RequestId': 'lCYc0YWhbQlmlobyRTggpTRV3pnsA3tbjs7PmVAzaZ13tKYAABDK', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'lCYc0YWhbQlmlobyRTggpTRV3pnsA3tbjs7PmVAzaZ13tKYAABDK'}, 'RetryAttempts': 0}, 'Buckets': [], 'Owner': {'DisplayName': 'webfile', 'ID': 'bcaf1ffd86f41161ca5fb16fd081034f'}}
.
```

I'm running the server from the CLI, not docker image. Seems to be working fine, I'm able to `apply` and `destroy`, but the server log does have some 404s e.g. 
```bash
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?lifecycle= HTTP/1.1" 404 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?replication= HTTP/1.1" 404 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?encryption= HTTP/1.1" 404 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?object-lock= HTTP/1.1" 404 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "HEAD /my-tf-test-bucket HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?tagging= HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "PUT /my-tf-test-bucket?acl= HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2023 12:15:17] "GET /my-tf-test-bucket?acl= HTTP/1.1" 200 -
```

**Comment by WesleyHindle** [comment]
Also, are there only certain services available when using moto to deploy TF resources locally? 

When I go to `http://localhost:5000/moto-api/` the only service listed are: CloudWatch, Core, Events, IAM, S3 and STS. And when I tried to deploy a basic Lambda moto server crashed.

**Comment by bblommers** [comment]
Yes, I would consider that best practice @WesleyHindle. Specifying the endpoint makes it really obvious that these tests only work if there is a Server running.

The 404's are expected actually - that's just AWS' (and Moto's) way of telling Terraform that these object locks/encryption configurations have not been set.

Regarding the errors: have you installed Moto with `moto[server]`? That should install all required dependencies. If you only install `moto`, it wouldn't install the Docker-dependency that you need for AWSLambda.

**Comment by WesleyHindle** [comment]
I hadn't before. So I've uninstalled `moto` and reinstalled with pip3 install 'moto[server]', but now when I run `moto_server` I just get `zsh: command not found: moto_server`

**Comment by WesleyHindle** [comment]
It was the pedantic quotes! Thank you. 

When I go to http://localhost:5000/moto-api/ the only service listed are: CloudWatch, Core, Events, IAM, S3 and STS. After deploying the Lambda more services were shown. Does this API page's content change depending on what you have deployed?

Just curious: Why does `pip install moto` not install the deps that `moto[server]`, when the former installs for all services (I think)?

**Comment by bblommers** [comment]
The page only shows services that have been loaded into memory, so yes, it depends on what you have deployed.

`pip install moto` does not install all dependencies actually, only the basic ones. You should always list the services that you use as extras, so that Moto installs all dependencies for those services: e.g. `pip install moto[awslambda]`, `pip install moto[ec2,s3]`, or just `pip install moto[all]` if you don't care about the install-time/size of the dependencies.

**Comment by WesleyHindle** [comment]
Thank you for the clarification. Last question, hopefully for a while!

When using the moto server can you make calls to the AWS API on the CLI which go to the server, rather than your real AWS account?

**Comment by bblommers** [comment]
Yes, you can specify the endpoint URL in the CLI as well!
`aws ec2 whatever --endpoint-url http://localhost:5000`

**Comment by WesleyHindle** [comment]
Thank you for that. 

If I deployed TF infra using moto server and then wanted to write tests to check something checking an unauthorised user couldn't create a bucket how would I do this regarding test fixtures:

1. By building on top of previous fixtures e.g.
```python
@pytest.fixture
@mock_s3
@mock_iam
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"

@pytest.fixture
def iam(aws_credentials):
    with mock_iam():
        yield(boto3.client (
            service_name='iam',
            region_name='eu-west-2',
            endpoint_url='http://localhost:5000'
            ))


@pytest.fixture
def s3(iam):
    with mock_lambda():
        yield(boto3.client (
            service_name='s3',
            region_name='eu-west-2',
            endpoint_url='http://localhost:5000'
            ))
```

2. Or by having separate fixtures for separate services using `aws_credentials` as a parameter separately:
```python
@pytest.fixture
@mock_s3
@mock_iam
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"

@pytest.fixture
def iam(aws_credentials):
    with mock_iam():
        yield(boto3.client (
            service_name='iam',
            region_name='eu-west-2',
            endpoint_url='http://localhost:5000'
            ))


@pytest.fixture
def s3(aws_credentials):
    with mock_lambda():
        yield(boto3.client (
            service_name='s3',
            region_name='eu-west-2',
            endpoint_url='http://localhost:5000'
            ))
```

And if you get to the point where you're writing tests like:
```python
def invalid_user_s3(s3, iam)
 # create iam user
 # assert iam_user.create_bucket == response["code"] == "401"
```

Then it's time to move to a more suitable tool?

**Comment by bblommers** [comment]
Regarding the fixtures: Personally I prefer the second version, because it's obvious when seeing the test that both mocks are active. But it is a personal preference, both should work.

-----------------------------

The authentication:
By default, all actions are allowed, just to make things as easy as possible. It is possible to configure Moto to authenticate requests, and return 401's if the provided user does not have roles with the correct permissions, but the implementation is far from complete. 
The docs are here: http://docs.getmoto.org/en/latest/docs/iam.html

The docs don't explcitly mention this, but the decorator only works for in-memory Moto tests. If you use the MotoServer, you would have to use the environment variable. 

So it's a bit difficult if you only have a single test where you want to verify authentication. With an environment variable, this would have to be set on server startup, and you would need a dedicated MotoServer instance just for this test - otherwise all subsequent tests suddenly also need authentication.


Feel free to open a new feature request to improve this, if you do want to go down this road - maybe we can offer an API to toggle authentication on/off on demand.

--------------------

The error message is Docker-specific, and just means that Moto can't connect to the Docker engine. There are some possible fixes here: https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version
