### ISSUE TITLE
S3: `put_bucket_lifecyle` with multiple Transitions

### ISSUE THREAD

**Issue by ccatterina** [getmoto/moto#6388]
Hi,
Moto implements the `put_bucket_lifecycle` API that should expect an array of [AWS S3 Rule](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Rule.html) objects as input.
From what I understand from looking at the code, moto implementation instead of parsing a `Rule` parse an object very similar to a [AWS S3 Lifecycle Rule](https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleRule.html)  with the only exception that accept a single `Transition` instead of an array of `Transitions`.

To fix this issue probably the best thing to do is to implement the [`put_bucket_lifecycle_configuration`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html) API, that expect an array of `Lifecycle Rule`  objects (like the current rules but with an array of `Transition` instead of a single `Transition`), and fix the current  [`put_bucket_lifecycle`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycle.html) API in order to make it to accept an Array of  `Rule` objects.

What do you think about it?

if it's okay with you I could work on it and open a PR.

**Comment by bblommers** [comment]
Hi @ccatterina! We do already support `put_bucket_lifecycle_configuration`, as all our tests use that method: https://github.com/getmoto/moto/blob/master/tests/test_s3/test_s3_lifecycle.py

I'm assuming that `boto3` automatically translates `put_bucket_lifecycle`, so that the incoming request for both methods look the same.
We then process them here: 
https://github.com/getmoto/moto/blob/7b4cd492ffa6768dfbd733b3ca5f55548d308d00/moto/s3/models.py#L1793

Having multiple Transitions indeed fails against Moto, so if you want to create a fix (+ testcase) for this, that would be very welcome! Let us know if you need any help with this.

**Comment by ccatterina** [comment]
> I'm assuming that boto3 automatically translates put_bucket_lifecycle, so that the incoming request for both methods look the same.

Oh, ok. I didn't realize that! In that case it could also be helpful update the documentation, which now says that `put_bucket_lifecycle_configuration` is not supported.

> Having multiple Transitions indeed fails against Moto, so if you want to create a fix (+ testcase) for this, that would be very welcome! Let us know if you need any help with this.

Sure, I'll work on it in the coming weeks! I will open a PR as soon as I have something ready.
