### ISSUE TITLE
Docstring is not fully correct

### ISSUE THREAD

**Issue by beliaev-maksim** [getmoto/moto#6433]
I see following text: `For all versions, we need to add passthrough to allow non-AWS requests to work`

but actual code passes only HTTP traffic. I think doc string is not 100% correct. Since non-AWS request could be also in HTTPS.

I would recommend to research options to allow more traffic through, eg via regex

https://github.com/getmoto/moto/blob/af4a8e2ba6faf0c95d836f8cb66d73d80bd6250b/moto/core/custom_responses_mock.py#LL163C1-L163C1

**Comment by bblommers** [comment]
Just looked into this a little bit more, but I think the current docs/behaviour is correct. Because the `passthru` is a string, `responses` will use a simple `startswith`-check. And HTTPS requests will also start with `http`.

https://github.com/getsentry/responses/blob/10d0473a8405264033da434c4f3c09cf6463cc2e/responses/__init__.py#L1026

**Comment by beliaev-maksim** [comment]
you are right, we add a prefix anyway when call `add_passthru`
