### ISSUE TITLE
Add `tag_resources` support to resourcegroupstaggingapi

### ISSUE THREAD

**Issue by klauern** [getmoto/moto#6688]
This is in addition to https://github.com/getmoto/moto/issues/6669 which was for the `log` API endpoint.  This also applies to the `resourcegroupstaggingapi` endpoint.

**Comment by bblommers** [comment]
Hi @klauern, welcome to Moto!

Support for the `resourcegroupstaggingapi` is a bit trickier, because it supports tagging all the services. There is no centralized tagging mechanism in Moto (yet), so this means we will have to implement this feature for every service separately. I imagine that we'll only implement support for a few services/resources at the time, based on what is required. 

Is there a specific service-resource(s) that you want to tag using this API?

**Comment by klauern** [comment]
I was using [CloudCustodian](cloudcustodian.io) to write some policies around tagging/archival tasks around RDS DB cluster snapshot ages, and it apparently uses that API to get the tagging done.  It took a bit of fiddling to figure that out, but when the test started erroring on `tag_resources`, I found it wasn't using the RDS mock in the test for that action.  I'm not sure what other places CC uses that API, but it does seem like a fallback mechanism/simplification for tagging suport across different resources with an ARN
