### ISSUE TITLE
How about using `ruff` for linter instead of flake8, black and pylint?

### ISSUE THREAD

**Issue by tsugumi-sys** [getmoto/moto#6739]
I think [ruff ](https://beta.ruff.rs/docs/) is a good choice for fast python linter.

## Performance

I compare the processing time of each linters in this project and the results are below.

| try count | ruff | flake8 | pylint |
| :---: | :---: | :---: | :---: |
| 1 | 365 ms | 53780 ms |  58750 ms |
| 2 | 374 ms | 53410 ms |   67330 ms |
| 3 | 364 ms | 55460 ms | 62750 ms |

check codes:
```Makefile

lint-flake8:
	@echo "Running flake8..."
	flake8 moto tests

lint-pylint:
	@echo "Running pylint..."
	pylint -j 0 moto tests

lint-ruff:
	@echo "Running ruff..."
	ruff moto/ tests/
```

## Migration Steps

1. List linting errors caused by ruff (still use flake8 and pylint).
2. Fix the linting errors above.
3. Migrating to `ruff` completely (Makefile, Github Actions, e.t.c).

Currently, 4428 errors are found by ruff! (Many of them are `E501 Line too long`)

**Comment by bblommers** [comment]
I'm OK with replacing `flake8` with `ruff`. The `pylint` integration does not have full parity, so I'd like to keep `pylint` along side for now.

The line-length issues are a matter of opinion, I suppose. I'd prefer to keep the current (black) style, where lines can be > 88 characters if it makes sense.
It looks like we can easily ignore that rule:
```
ruff moto tests --ignore E501
```

**Comment by bblommers** [comment]
`ruff` also throws a lot of error where we should be using `isinstance` instead of `type() == ..`. I was a little surprised that `flake8` is not catching that, but that's just because we're using an outdated version. Upgrading to `flake8==6.1.0` throws the same errors.

So it looks like `ruff` does indeed do the same job as `flake8`, just.. incredibly fast.

**Comment by tsugumi-sys** [comment]
Ok, then I need to create ignore list for ruff first and fix them one by one :)

**Comment by kbalk** [comment]
`pylint` catches non-usage of `isinstance` unless you have that feature turned off.  I fixed `type() == ...` occurances when I was removing `surer` usage, so that's some files, but not all.

Line lengths for tools are over the place.  `black` wants 88, `pylint` compromises on 100.  Again, I fixed line lengths to 100 when the warning came up, but that could be an issue if the line length was enforced for `black`.

There are different line length restrictions for docstrings, but docstrings aren't currently enforced (`pylint` warnings aren't currently active for docstring-related issues).
