### ISSUE TITLE
s3 copy_from w/ CopySourceIfNoneMatch with same etag does not result in a PreconditionFailed error when mocked

### ISSUE THREAD

**Issue by rstevens011** [getmoto/moto#7868]
Given a bucket with an existing object's e_tag, *xyz*, with the following bits of code:

```
s3 = boto3.resource("s3")
obj = s3.Object("bucketName", "keyOfObject") # keyOfObject has etag "xyz"; bucketName has versioning enabled
copy_from_kwargs = {
            "CopySource": {
                "Bucket": "anotherBucketName",
                "Key": "aDifferentKey",
            },
            "CopySourceIfNoneMatch": "xyz"
        }

obj.copy_from(**copy_from_kwargs)
```

Boto3 will return a `PreconditionFailed` error.  However, when I use moto when mocking the  copy_from response, there is no `PreconditionFailed` exception returned.  It proceeds to "create" a new object with *a different version ID*.  The intent of my code here is to prevent creation of a new version ID **if** the e tag value is the same. It appears there is some deviation between what happens server side and what moto is doing.

In the above example, **xyz** is used for illustrative purposes and is not a valid etag. A etag will contain a string with double quotes prefixing and suffixing the hash - I tried calling copy_from using moto with and without the double quotes and the same behaviour occurs as described above. e.g.:

```
copy_from_kwargs = {
            "CopySource": {
                "Bucket": "anotherBucketName",
                "Key": "aDifferentKey",
            },
            "CopySourceIfNoneMatch": '"xyx"'
        }
```

 Note, boto3 itself seems to not care if they are or are not included.

I am using moto 5.0.9.

Boto docs: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/objectsummary/copy_from.html

**Comment by bblommers** [comment]
Hi @rstevens011, thanks fo raising this! I've opened a PR with a fix for this bug.

Note that your example also throws an `InvalidRequest`-exception when ran against AWS:
`This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.`

Moto now throws the same exception. Based on my own testing, copying an item in place only succeeds if:
 - the bucket is not versioned
 - any `metadata, storage class, website redirect location or encryption attributes` is specified
 - if the VersionId-parameter is supplied
