### ISSUE TITLE
confusing pytest fixture example

### ISSUE THREAD

**Issue by soxofaan** [getmoto/moto#7892]
I'm a bit confused about the pytest fixture example, currently at http://docs.getmoto.org/en/latest/docs/getting_started.html#example-on-usage

https://github.com/getmoto/moto/blob/b6bb11e6ef4c3c1e51e94278237ee7db65b0c89f/docs/docs/getting_started.rst?plain=1#L264-L268

This test function `def test_s3_directly(aws):` requests the `aws` fixture, but then uses variable `s3` in its body. I think `s3` should be replaced with `aws` here.
Or vise-versa: I suspect the original intention of the test snippet was to actually define the fixture as `def s3(aws_credentials):` instead of `def aws(aws_credentials):`. Could that be the case?

https://github.com/getmoto/moto/blob/b6bb11e6ef4c3c1e51e94278237ee7db65b0c89f/docs/docs/getting_started.rst?plain=1#L256-L262

Both these fixture definitions request the `aws` fixture but don't use it. Is that intentional? (For example to illustrate that you can mix fixture generate clients and your own)   I think it makes sense to illustrate that flexibility by having one of them use the `aws` fixture, and the other just request `aws_credentials`. e.g.:

```python
@pytest.fixture
def create_bucket1(aws):
    aws.create_bucket(Bucket="bb1")

@pytest.fixture
def create_bucket2(aws_credentials):
    boto3.client("s3").create_bucket(Bucket="bb2")
```

And final note: the doc subsection of the snippet is just called "Example on usage", but I thinks it's useful to mention pytest in the title, e.g. "Pytest fixture usage example".

**Comment by bblommers** [comment]
Hi @soxofaan! Thanks for your feedback on this. 

> I suspect the original intention of the test snippet was to actually define the fixture as def s3(aws_credentials):

It was called `def s3(..)` in an earlier iteration of the docs, actually! We've since changed the fixture-name to `aws`, but apparently forgot to update the variable name as well.

The attached PR improves the documentation - you can see a preview of the new docs here:
https://moto--7949.org.readthedocs.build/en/7949/docs/getting_started.html#pytest-fixtures-example-usage

Does that make more sense, and/or do you see any other improvements?
