### ISSUE TITLE
API GatewayV2 GetApi with an empty string: not implemented

### ISSUE THREAD

**Issue by juanitosvq** [getmoto/moto#7974]
Hi, I am trying to test the use case where I try to get a REST API with an empty string.

Using the AWS API, I receive a 200 OK with no content:
```
import boto3
import json

client = boto3.session.Session().client("apigatewayv2")
resp = client.get_api(ApiId="")

print(json.dumps(resp, default=str))
```

Response:
```
{
    "ResponseMetadata": {
        "RequestId": "1234567890",
        "HTTPStatusCode": 200,
        "HTTPHeaders": {
            "date": "Tue, 13 Aug 2024 12:06:06 GMT",
            "content-type": "application/json",
            "content-length": "14951",
            "connection": "keep-alive",
            "x-amzn-requestid": "1234567890",
            "x-amz-apigw-id": "1234567890"
        },
        "RetryAttempts": 0
    }
}
```

When using `moto`, I get a 404, `Not yet implemented` response:
```
import boto3
import moto

with moto.mock_aws():
    client = boto3.session.Session(region_name="us-east-1").client("apigatewayv2")

    resp = client.get_api(ApiId="")
```

I've been looking through the code to have a go at adding this myself, but I am a bit stuck, so I'd appreciate some guidance. I don't think I have enough to open a draft PR, that's why I opened this as an issue.

I changed the URL regex in `apigatewayv2/urls.py` to be `*` instead of `+` , to make my test case get a bit further:
```
"{0}/v2/apis/(?P<api_id>[^/]*)$": ApiGatewayV2Response.dispatch,
```
but the [uri_to_regexp](https://github.com/getmoto/moto/blob/master/moto/core/responses.py#L504) still returns a regex that will not match the uri of the request when the `ApiId` is an empty string.

Any feedback will be appreciated!

**Comment by bblommers** [comment]
Hi @juanitosvq, thanks for trying to fix this in Moto! That is quite odd behaviour from AWS - I would expect them to return a `400` here instead.

The dispatch-method uses the URL's supplied by `botocore`, and botocore seems to also always expect the `api_id` to have some value.

Instead of fighting the url-matcher, and challenging/changing all the assumptions that the `dispatch`-method makes, I would suggest adding a custom method to handle this use-case. It is an outlier - I don't think I've seen anything else like this from AWS - so I'm not opposed to having a custom handler to solve this.

```
diff --git a/moto/apigatewayv2/responses.py b/moto/apigatewayv2/responses.py
index 18d6b1b83..553b1b8e7 100644
--- a/moto/apigatewayv2/responses.py
+++ b/moto/apigatewayv2/responses.py
@@ -20,6 +20,9 @@ class ApiGatewayV2Response(BaseResponse):
         """Return backend instance specific for this region."""
         return apigatewayv2_backends[self.current_account][self.region]
 
+    def get_api_without_id(self, *args):
+        return 200, {}, "{}"
+
     def create_api(self) -> TYPE_RESPONSE:
         params = json.loads(self.body)
 
diff --git a/moto/apigatewayv2/urls.py b/moto/apigatewayv2/urls.py
index 72f4922d6..013550a8e 100644
--- a/moto/apigatewayv2/urls.py
+++ b/moto/apigatewayv2/urls.py
@@ -9,6 +9,7 @@ url_bases = [
 
 url_paths = {
     "{0}/v2/apis$": ApiGatewayV2Response.dispatch,
+    "{0}/v2/apis/$": ApiGatewayV2Response.get_api_without_id,
     "{0}/v2/apis/(?P<api_id>[^/]+)$": ApiGatewayV2Response.dispatch,
     "{0}/v2/apis/(?P<api_id>[^/]+)/authorizers$": ApiGatewayV2Response.dispatch,
     "{0}/v2/apis/(?P<api_id>[^/]+)/authorizers/(?P<authorizer_id>[^/]+)$": ApiGatewayV2Response.dispatch,
```
If you could just add a small comment inside the new method to explain this usecases this serves, that would minimize future head scratching. :slightly_smiling_face: 

Note that I haven't linted this yet, so make sure to run `make lint` at the end to make sure our CI is happy - see https://docs.getmoto.org/en/latest/docs/contributing/installation.html#installing-moto-locally
